spring:
  application:
    name: rtr-backend
  datasource:
    poolSize: 20
    minIdle: 1
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5431/rtr
    username: rtr
    password: password
    tomcat:
      test-while-idle: true
      test-on-borrow: true
      validation-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false


elastic-index:
  basicTenantIndexes:
    "no": basic_test_nkom
    bh: basic_test_bh
    at: basic_test_aus
  basicQosTenantIndexes:
    "no": basic_qos_test_nkom
    bh: basic_qos_test_bh
    at: basic_qos_test_aus
  keepAlive: keep_alive

client-tenant:
  clientTenantMapping:
    bh: sah
    "no": nkom
    at: austria
  defaultTenant: bh

measurement-server:
  host: http://localhost:8080
  slotWindow: 5
  defaultProviderId: 6


---
spring:
  profiles: dev

measurement-server:
  host: ${CONTROL_SERVER_HOST}

client-tenant:
  clientTenantMapping:
    bh: bh_dev
    "no": no_dev
    at: at_dev
  defaultTenant: bh
